In [22]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [23]:
# This function was coded by Lars, but modified to save to dataframe

def get_sat_values(filename):
    PDOP, HDOP, VDOP, latitude, longitude, num_used_satellites, altitude = [], [], [], [], [], [], []

    with open(filename, 'r') as file:
        lines = file.readlines()
        # divide messages
        messages = [lines[i:i + 7] for i in range(0, len(lines), 7)]

        for message in messages:
            PDOP.append(float(message[0].split(',')[15]))
            HDOP.append(float(message[0].split(',')[16]))
            VDOP.append(float(message[0].split(',')[17][:3]))
            latitude.append(float(message[6].split(',')[2:3][0]))
            longitude.append(float(message[6].split(',')[4:5][0]))
            num_used_satellites.append(int(message[6].split(',')[6]))
            altitude.append(float(message[6].split(',')[9:10][0]))

    # Create a DataFrame
    df = pd.DataFrame({
        'PDOP': PDOP,
        'HDOP': HDOP,
        'VDOP': VDOP,
        'latitude': latitude,
        'longitude': longitude,
        'num_used_satellites': num_used_satellites,
        'altitude': altitude
    })

    return df

In [24]:
# load the files within folder /data/fingerprints into a list
nmea_path = os.getcwd() + '/data/nmea_data_assignment3'
nmea_files = os.listdir(nmea_path)

# load the nmea files into a list of dataframes
nmea_dict = {}

for file in nmea_files:
    try:
        nmea_dict[file] = get_sat_values(nmea_path + '/' + file)
        # divide latitude and longitude by 100 to get the correct value
        nmea_dict[file]['latitude'] = nmea_dict[file]['latitude'] / 100
        nmea_dict[file]['longitude'] = nmea_dict[file]['longitude'] / 100
        nmea_dict[file]['ID'] = file
    except Exception as e:
        print(f"error reading file {file}: {e}")
        continue

In [25]:
nmea_dict['1.log']

,PDOP,HDOP,VDOP,latitude,longitude,num_used_satellites,altitude,ID
0,1.2,1.0,0.7,52.001292,4.224733,12,-0.0,1.log
1,1.2,1.0,0.7,52.001291,4.224733,12,0.0,1.log
2,1.2,1.0,0.7,52.001290,4.224736,12,0.1,1.log
3,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
4,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
5,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
6,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
7,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
8,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
9,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
10,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
11,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
12,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
13,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
14,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
15,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
16,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
17,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
18,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log
19,1.2,1.0,0.7,52.001288,4.224737,12,0.3,1.log

In [28]:
print(nmea_dict.items())

dict_items([('4.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.7  52.001417   4.225590                   12       1.4
1    1.2   1.0   0.7  52.001417   4.225590                   12       1.4
2    1.2   1.0   0.7  52.001417   4.225590                   12       1.4
3    1.2   1.0   0.7  52.001417   4.225590                   12       1.4
4    1.2   1.0   0.7  52.001416   4.225598                   12       1.3
5    1.2   1.0   0.7  52.001415   4.225599                   12       1.3
6    1.2   1.0   0.7  52.001414   4.225601                   12       1.4
7    1.2   1.0   0.6  52.001412   4.225603                   12       1.4
8    1.2   1.0   0.6  52.001412   4.225602                   12       1.4
9    1.2   1.0   0.7  52.001412   4.225602                   12       1.4
10   1.2   1.0   0.7  52.001412   4.225602                   12       1.4
11   1.2   1.0   0.7  52.001412   4.225602                   12       1.4
12   1.2   1.0   0.7  52.001415   4.225600                   12       1.2
13   1.2   1.0   0.7  52.001415   4.225600                   12       1.2
14   1.2   1.0   0.7  52.001415   4.225602                   12       1.2
15   1.2   1.0   0.7  52.001415   4.225602                   12       1.2
16   1.2   1.0   0.7  52.001415   4.225602                   12       1.2
17   1.2   1.0   0.7  52.001415   4.225602                   12       1.2
18   1.2   1.0   0.7  52.001415   4.225602                   12       1.2
19   1.2   1.0   0.7  52.001415   4.225602                   12       1.2

       ID
0   4.log
1   4.log
2   4.log
3   4.log
4   4.log
5   4.log
6   4.log
7   4.log
8   4.log
9   4.log
10  4.log
11  4.log
12  4.log
13  4.log
14  4.log
15  4.log
16  4.log
17  4.log
18  4.log
19  4.log  ), ('5.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.7  52.001420   4.225675                   12       1.3
1    1.2   1.0   0.6  52.001422   4.225676                   12       1.2
2    1.2   1.0   0.6  52.001422   4.225674                   12       0.9
3    1.2   1.0   0.6  52.001423   4.225673                   12       0.9
4    1.2   1.0   0.6  52.001421   4.225671                   12       1.0
5    1.2   1.0   0.6  52.001421   4.225670                   12       0.9
6    1.2   1.0   0.6  52.001419   4.225668                   12       1.1
7    1.2   1.0   0.6  52.001419   4.225668                   12       1.1
8    1.2   1.0   0.6  52.001418   4.225670                   12       1.1
9    1.2   1.0   0.6  52.001418   4.225667                   12       1.1
10   1.2   1.0   0.6  52.001421   4.225667                   12       1.1
11   1.2   1.0   0.7  52.001423   4.225663                   12       1.1
12   1.2   1.0   0.7  52.001423   4.225663                   12       1.0
13   1.2   1.0   0.7  52.001424   4.225661                   12       1.1
14   1.2   1.0   0.7  52.001424   4.225663                   12       1.2
15   1.2   1.0   0.7  52.001423   4.225660                   12       1.2
16   1.2   1.0   0.7  52.001423   4.225660                   12       1.2
17   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
18   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
19   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
20   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
21   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
22   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
23   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
24   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
25   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
26   1.2   1.0   0.6  52.001422   4.225656                   12       1.2
27   1.2   1.0   0.6  52.001419   4.225647                   12       0.9
28   1.2   1.0   0.6  52.001419   4.225647                   12       0.9
29   1.2   1.0   0.6  52.001419   4.225647                   12       0.9

       ID
0   5.log
1   5.log
2   5.log
3   5.log
4   5.log
5   5.log
6   5.log
7   5.log
8   5.log
9   5.log
10  5.log
11  5.log
12  5.log
13  5.log
14  5.log
15  5.log
16  5.log
17  5.log
18  5.log
19  5.log
20  5.log
21  5.log
22  5.log
23  5.log
24  5.log
25  5.log
26  5.log
27  5.log
28  5.log
29  5.log  ), ('7.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.7   1.3   1.1  52.001842   4.225498                   12       2.4
1    2.5   1.8   1.7  52.001842   4.225502                   12       2.4
2    2.2   1.6   1.6  52.001840   4.225499                   12       2.4
3    2.9   2.0   2.1  52.001838   4.225497                   12       2.4
4    2.8   1.9   2.1  52.001834   4.225501                   12       2.4
5    3.0   2.0   2.2  52.001836   4.225507                   12       2.5
6    3.9   2.6   3.0  52.001838   4.225508                   12       2.5
7    3.5   2.2   2.7  52.001838   4.225511                   12       2.5
8    3.5   2.2   2.7  52.001838   4.225511                   12       2.5
9    4.3   2.6   3.3  52.001837   4.225517                   12       2.6
10   2.2   1.4   1.7  52.001836   4.225519                   12       2.5
11   3.2   2.0   2.5  52.001835   4.225516                   12       2.5
12   2.9   1.8   2.3  52.001834   4.225516                   12       2.5
13   2.9   1.8   2.4  52.001832   4.225519                   12       2.5
14   3.5   2.1   2.8  52.001834   4.225515                   12       2.5
15   3.1   1.9   2.5  52.001837   4.225510                   12       2.5
16   3.7   2.3   2.9  52.001842   4.225504                   12       2.5
17   3.1   1.9   2.4  52.001843   4.225501                   12       2.5
18   2.1   1.3   1.7  52.001844   4.225496                   12       2.5
19   1.9   1.2   1.5  52.001844   4.225496                   12       2.6
20   2.2   1.4   1.7  52.001844   4.225495                   12       2.6
21   2.5   1.5   1.9  52.001847   4.225495                   12       2.4
22   2.9   1.8   2.3  52.001848   4.225496                   12       2.4
23   3.3   2.0   2.6  52.001847   4.225494                   12       2.4
24   3.1   1.9   2.4  52.001845   4.225492                   12       2.4
25   3.8   2.3   3.0  52.001842   4.225491                   12       2.4
26   1.4   0.9   1.1  52.001841   4.225489                   12       2.4
27   1.4   0.9   1.1  52.001840   4.225487                   12       2.4
28   1.2   1.0   0.7  52.001843   4.225490                   12       2.5
29   1.2   1.0   0.7  52.001843   4.225490                   12       2.5

       ID
0   7.log
1   7.log
2   7.log
3   7.log
4   7.log
5   7.log
6   7.log
7   7.log
8   7.log
9   7.log
10  7.log
11  7.log
12  7.log
13  7.log
14  7.log
15  7.log
16  7.log
17  7.log
18  7.log
19  7.log
20  7.log
21  7.log
22  7.log
23  7.log
24  7.log
25  7.log
26  7.log
27  7.log
28  7.log
29  7.log  ), ('6.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.6  52.001892   4.225602                   12       2.1
1    1.2   1.0   0.6  52.001889   4.225600                   12       2.3
2    1.2   1.0   0.6  52.001892   4.225602                   12       2.3
3    1.2   1.0   0.6  52.001891   4.225601                   12       2.3
4    1.2   1.0   0.6  52.001890   4.225601                   12       2.3
5    1.2   1.0   0.6  52.001894   4.225602                   12       2.4
6    1.2   1.0   0.6  52.001895   4.225598                   12       2.5
7    1.2   1.0   0.6  52.001895   4.225600                   12       2.4
8    1.2   1.0   0.6  52.001896   4.225599                   12       2.4
9    1.2   1.0   0.6  52.001900   4.225600                   12       2.5
10   1.2   1.0   0.6  52.001901   4.225597                   12       2.6
11   1.2   1.0   0.6  52.001900   4.225593                   12       2.5
12   1.2   1.0   0.6  52.001900   4.225593                   12       2.5
13   1.2   1.0   0.6  52.001900   4.225593                   12       2.5
14   1.2   1.0   0.6  52.001900   4.225593                   12       2.5
15   1.2   1.0   0.6  52.001899   4.225585                   12       2.6
16   1.2   1.0   0.6  52.001900   4.225584                   12       2.6
17   1.2   1.0   0.6  52.001899   4.225581                   12       2.7
18   1.2   1.0   0.7  52.001901   4.225586                   12       2.7
19   1.2   1.0   0.6  52.001902   4.225584                   12       2.7
20   1.2   1.0   0.7  52.001902   4.225584                   12       2.7
21   1.2   1.0   0.7  52.001902   4.225584                   12       2.7

       ID
0   6.log
1   6.log
2   6.log
3   6.log
4   6.log
5   6.log
6   6.log
7   6.log
8   6.log
9   6.log
10  6.log
11  6.log
12  6.log
13  6.log
14  6.log
15  6.log
16  6.log
17  6.log
18  6.log
19  6.log
20  6.log
21  6.log  ), ('2.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.6  52.001384   4.225109                   12       1.6
1    1.2   1.0   0.6  52.001384   4.225109                   12       1.6
2    1.2   1.0   0.6  52.001382   4.225109                   12       1.4
3    1.2   1.0   0.6  52.001380   4.225108                   12       1.3
4    1.2   1.0   0.6  52.001379   4.225115                   12       1.4
5    1.2   1.0   0.6  52.001379   4.225114                   12       1.5
6    1.2   1.0   0.6  52.001379   4.225114                   12       1.5
7    1.2   1.0   0.6  52.001379   4.225114                   12       1.5
8    1.2   1.0   0.6  52.001379   4.225114                   12       1.5
9    1.2   1.0   0.6  52.001379   4.225114                   12       1.5
10   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
11   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
12   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
13   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
14   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
15   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
16   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
17   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
18   1.2   1.0   0.6  52.001379   4.225114                   12       1.5
19   1.2   1.0   0.6  52.001381   4.225096                   12       1.2
20   1.2   1.0   0.6  52.001381   4.225096                   12       1.2
21   1.2   1.0   0.6  52.001381   4.225096                   12       1.2
22   1.2   1.0   0.6  52.001381   4.225096                   12       1.2
23   1.2   1.0   0.6  52.001383   4.225104                   12       0.8
24   1.2   1.0   0.6  52.001383   4.225104                   12       0.9

       ID
0   2.log
1   2.log
2   2.log
3   2.log
4   2.log
5   2.log
6   2.log
7   2.log
8   2.log
9   2.log
10  2.log
11  2.log
12  2.log
13  2.log
14  2.log
15  2.log
16  2.log
17  2.log
18  2.log
19  2.log
20  2.log
21  2.log
22  2.log
23  2.log
24  2.log  ), ('3.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.6  52.001423   4.225530                   12       1.4
1    1.2   1.0   0.6  52.001423   4.225530                   12       1.4
2    1.2   1.0   0.7  52.001423   4.225530                   12       1.4
3    1.2   1.0   0.7  52.001423   4.225530                   12       1.4
4    1.2   1.0   0.7  52.001423   4.225530                   12       1.4
5    1.2   1.0   0.7  52.001423   4.225529                   12       1.8
6    1.2   1.0   0.7  52.001422   4.225530                   12       1.9
7    1.2   1.0   0.7  52.001422   4.225530                   12       1.9
8    1.2   1.0   0.7  52.001422   4.225530                   12       1.9
9    1.2   1.0   0.7  52.001422   4.225530                   12       1.9
10   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
11   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
12   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
13   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
14   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
15   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
16   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
17   1.2   1.0   0.7  52.001422   4.225530                   12       1.9
18   1.2   1.0   0.6  52.001422   4.225530                   12       1.9
19   1.2   1.0   0.6  52.001422   4.225530                   12       1.9

       ID
0   3.log
1   3.log
2   3.log
3   3.log
4   3.log
5   3.log
6   3.log
7   3.log
8   3.log
9   3.log
10  3.log
11  3.log
12  3.log
13  3.log
14  3.log
15  3.log
16  3.log
17  3.log
18  3.log
19  3.log  ), ('1.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.7  52.001292   4.224733                   12      -0.0
1    1.2   1.0   0.7  52.001291   4.224733                   12       0.0
2    1.2   1.0   0.7  52.001290   4.224736                   12       0.1
3    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
4    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
5    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
6    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
7    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
8    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
9    1.2   1.0   0.7  52.001288   4.224737                   12       0.3
10   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
11   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
12   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
13   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
14   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
15   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
16   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
17   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
18   1.2   1.0   0.7  52.001288   4.224737                   12       0.3
19   1.2   1.0   0.7  52.001288   4.224737                   12       0.3

       ID
0   1.log
1   1.log
2   1.log
3   1.log
4   1.log
5   1.log
6   1.log
7   1.log
8   1.log
9   1.log
10  1.log
11  1.log
12  1.log
13  1.log
14  1.log
15  1.log
16  1.log
17  1.log
18  1.log
19  1.log  ), ('8.log',     PDOP  HDOP  VDOP   latitude  longitude  num_used_satellites  altitude  \
0    1.2   1.0   0.6  52.001582   4.224825                   12      -0.2
1    1.2   1.0   0.6  52.001580   4.224823                   12      -0.1
2    1.2   1.0   0.6  52.001580   4.224824                   12      -0.1
3    1.2   1.0   0.6  52.001580   4.224824                   12      -0.1
4    1.2   1.0   0.6  52.001580   4.224824                   12      -0.1
5    1.2   1.0   0.6  52.001579   4.224827                   12       0.1
6    1.2   1.0   0.6  52.001580   4.224827                   12      -0.0
7    1.2   1.0   0.6  52.001580   4.224830                   12      -0.1
8    1.2   1.0   0.6  52.001579   4.224833                   12       0.0
9    1.2   1.0   0.6  52.001579   4.224833                   12       0.0
10   1.2   1.0   0.6  52.001579   4.224833                   12       0.0
11   1.2   1.0   0.6  52.001579   4.224833                   12       0.0
12   1.2   1.0   0.6  52.001579   4.224833                   12       0.0
13   1.2   1.0   0.6  52.001577   4.224842                   12       0.3
14   1.2   1.0   0.6  52.001577   4.224842                   12       0.3
15   1.2   1.0   0.6  52.001577   4.224842                   12       0.3
16   1.2   1.0   0.6  52.001581   4.224843                   12       0.3
17   1.2   1.0   0.6  52.001581   4.224843                   12       0.3
18   1.2   1.0   0.6  52.001581   4.224843                   12       0.3
19   1.2   1.0   0.6  52.001581   4.224843                   12       0.3

       ID
0   8.log
1   8.log
2   8.log
3   8.log
4   8.log
5   8.log
6   8.log
7   8.log
8   8.log
9   8.log
10  8.log
11  8.log
12  8.log
13  8.log
14  8.log
15  8.log
16  8.log
17  8.log
18  8.log
19  8.log  )])

In [57]:
# Initialize a list to store the average latitudes and longitudes
averages = []

# Loop through the dictionary and calculate the averages
for idx, df in enumerate(nmea_dict.values()):
    avg_lat = df['latitude'].mean()
    avg_lon = df['longitude'].mean()
    averages.append({'ID': idx, 'latitude': avg_lat, 'longitude': avg_lon})

# Convert the list of averages to a DataFrame
average_df = pd.DataFrame(averages)

# Displaying the resulting DataFrame
average_df.head()

   ID   latitude  longitude
0   0  52.001415   4.225599
1   1  52.001421   4.225662
2   2  52.001840   4.225502
3   3  52.001897   4.225594
4   4  52.001380   4.225110

In [58]:
# save to csv
average_df.to_csv('smartphone_points.csv', index=False)